allowBuilds:
    "@vscode/vsce-sign": true
    cpu-features: true
    keytar: true
    ssh2: true
minimumReleaseAgeExclude:
    - "@mimic-behavior/eslint-config"
    - "@mimic-behavior/oxfmt-config"
    - "@mimic-behavior/ssh2-sftp-client"
